LOAD_TRA ~%MOD_FOLDER%/sources/custom/02/english.tra~

COPY ~%MOD_FOLDER%/sources/custom/02/sounds~ ~lang/%EE_LANGUAGE%/sounds~
COPY ~%MOD_FOLDER%/sources/custom/02/wav~ ~override~

LAF ivp_add_soundset
  INT_VAR
    cd_battlecry1 = RESOLVE_STR_REF(@1)
    cd_hurt1 = RESOLVE_STR_REF(@2)
    cd_common1 = RESOLVE_STR_REF(@3)
    cd_common2 = RESOLVE_STR_REF(@4)
    cd_common3 = RESOLVE_STR_REF(@5)
    cd_action1 = RESOLVE_STR_REF(@6)
    cd_action2 = RESOLVE_STR_REF(@7)
    cd_action3 = RESOLVE_STR_REF(@8)
    cd_damage1 = RESOLVE_STR_REF(@9)
    cd_dying1 = RESOLVE_STR_REF(@10)
    cd_action4 = RESOLVE_STR_REF(@11)
    cd_criticalhit = RESOLVE_STR_REF(@12)
    cd_disrupted = RESOLVE_STR_REF(@13)
    cd_battlecry2 = RESOLVE_STR_REF(@14)
    cd_breaking_pt = RESOLVE_STR_REF(@15)
    cd_hurt2 = RESOLVE_STR_REF(@16)
    cd_morale_break2 = RESOLVE_STR_REF(@17)
    cd_select_name = RESOLVE_STR_REF(@70)
  STR_VAR cd_name = ~IVC02~
END
OUTER_SET ivp_name_ref = RESOLVE_STR_REF(@70)
APPEND ~M_ivcsnd.lua~ ~filenames_stringrefs['IVC02'] = {%ivp_name_ref%, 2}~
