LOAD_TRA ~%MOD_FOLDER%/sources/custom/10/english.tra~

COPY ~%MOD_FOLDER%/sources/custom/10/sounds~ ~lang/%EE_LANGUAGE%/sounds~
COPY ~%MOD_FOLDER%/sources/custom/10/wav~ ~override~

LAF ivp_add_soundset
  INT_VAR
    cd_common1 = RESOLVE_STR_REF(@1)
    cd_common2 = RESOLVE_STR_REF(@2)
    cd_common3 = RESOLVE_STR_REF(@3)
    cd_common4 = RESOLVE_STR_REF(@4)
    cd_action1 = RESOLVE_STR_REF(@5)
    cd_action2 = RESOLVE_STR_REF(@6)
    cd_action3 = RESOLVE_STR_REF(@7)
    cd_action4 = RESOLVE_STR_REF(@8)
    cd_battlecry1 = RESOLVE_STR_REF(@9)
    cd_battlecry2 = RESOLVE_STR_REF(@10)
    cd_battlecry3 = RESOLVE_STR_REF(@11)
    cd_battlecry4 = RESOLVE_STR_REF(@12)
    cd_battlecry5 = RESOLVE_STR_REF(@13)
    cd_attack1 = RESOLVE_STR_REF(@14)
    cd_criticalmiss = RESOLVE_STR_REF(@15)
    cd_damage1 = RESOLVE_STR_REF(@16)
    cd_dying1 = RESOLVE_STR_REF(@17)
    cd_select_name = RESOLVE_STR_REF(@70)
  STR_VAR cd_name = ~IVC10~
END
OUTER_SET ivp_name_ref = RESOLVE_STR_REF(@70)
APPEND ~M_ivcsnd.lua~ ~filenames_stringrefs['IVC10'] = {%ivp_name_ref%, 2}~
