LOAD_TRA ~%MOD_FOLDER%/sources/custom/09/english.tra~

COPY ~%MOD_FOLDER%/sources/custom/09/sounds~ ~lang/%EE_LANGUAGE%/sounds~
COPY ~%MOD_FOLDER%/sources/custom/09/wav~ ~override~

LAF ivp_add_soundset
  INT_VAR
    cd_battlecry1 = RESOLVE_STR_REF(@1)
    cd_common1 = RESOLVE_STR_REF(@2)
    cd_common2 = RESOLVE_STR_REF(@3)
    cd_common3 = RESOLVE_STR_REF(@4)
    cd_action1 = RESOLVE_STR_REF(@5)
    cd_damage1 = RESOLVE_STR_REF(@6)
    cd_dying1 = RESOLVE_STR_REF(@7)
    cd_action_rare1 = RESOLVE_STR_REF(@8)
    cd_battlecry2 = RESOLVE_STR_REF(@9)
    cd_breaking_pt = RESOLVE_STR_REF(@10)
    cd_select_name = RESOLVE_STR_REF(@70)
  STR_VAR cd_name = ~IVC09~
END
OUTER_SET ivp_name_ref = RESOLVE_STR_REF(@70)
APPEND ~M_ivcsnd.lua~ ~filenames_stringrefs['IVC09'] = {%ivp_name_ref%, 2}~
